name: Release

on:
  push:
    tags:
      - "v*"

env:
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  publish-c2patool-binaries:
    name: Publish c2patool binaries
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust_version: [stable]
        experimental: [false]
        include:
          - os: macos-latest
            artifact_name: c2patool_mac_universal.zip
            uploaded_asset_name: ${{ env.RELEASE_TAG }}-universal-apple-darwin.zip
            sbom_asset_name: ${{ env.RELEASE_TAG }}-universal-apple-darwin-sbom.json
          - os: ubuntu-latest
            artifact_name: c2patool_linux_intel.tar.gz
            uploaded_asset_name: ${{ env.RELEASE_TAG }}-x86_64-unknown-linux-gnu.tar.gz
            sbom_asset_name: ${{ env.RELEASE_TAG }}-x86_64-unknown-linux-gnu-sbom.json
          - os: windows-latest
            artifact_name: c2patool_win_intel.zip
            uploaded_asset_name: ${{ env.RELEASE_TAG }}-x86_64-pc-windows-msvc.zip
            sbom_asset_name: ${{ env.RELEASE_TAG }}-x86_64-pc-windows-msvc-sbom.json

    steps:
      - name: Checkout repository
        if: ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        if: ${{ env.RELEASE_TAG }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          components: llvm-tools-preview

      - name: Install cargo-sbom
        if: ${{ env.RELEASE_TAG }}
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sbom
          version: "0.9.1"

      - name: Cache Rust dependencies
        if: ${{ env.RELEASE_TAG }}
        uses: Swatinem/rust-cache@v2

      - name: Run make release
        if: ${{ env.RELEASE_TAG }}
        run: cd cli && make release

      - name: Upload binary to GitHub
        if: ${{ env.RELEASE_TAG }}
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.uploaded_asset_name }}
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true

      - name: Generate SBOM
        if: ${{ env.RELEASE_TAG }}
        run: cd cli && cargo sbom > c2patool-sbom.json

      - name: Upload SBOM to Github
        if: ${{ env.RELEASE_TAG }}
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cli/c2patool-sbom.json
          asset_name: ${{ matrix.sbom_asset_name }}
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true
